### ISSUE TITLE
ImportError: cannot import name 'url_encode' from 'werkzeug'.

### ISSUE THREAD

**Issue by philderbeast** [kuaka/airscore#44]
I followed the steps in the readme on the `formula_dev` branch and hit a problem:

```
> docker-compose up flask-dev
```

```
# localhost:5000

flask.cli.NoAppException
flask.cli.NoAppException: While importing "autoapp", an ImportError was raised:

Traceback (most recent call last):
  File "/home/sid/.local/lib/python3.8/site-packages/flask/cli.py", line 240, in locate_app
    __import__(module_name)
  File "/app/autoapp.py", line 3, in <module>
    from airscore.app import create_app
  File "/app/airscore/app.py", line 8, in <module>
    from airscore import commands, public, user
  File "/app/airscore/public/__init__.py", line 3, in <module>
    from . import views  # noqa
  File "/app/airscore/public/views.py", line 15, in <module>
    from airscore.extensions import login_manager
  File "/app/airscore/extensions.py", line 10, in <module>
    from flask_wtf.csrf import CSRFProtect
  File "/home/sid/.local/lib/python3.8/site-packages/flask_wtf/__init__.py", line 17, in <module>
    from .recaptcha import *
  File "/home/sid/.local/lib/python3.8/site-packages/flask_wtf/recaptcha/__init__.py", line 2, in <module>
    from .fields import *
  File "/home/sid/.local/lib/python3.8/site-packages/flask_wtf/recaptcha/fields.py", line 3, in <module>
    from . import widgets
  File "/home/sid/.local/lib/python3.8/site-packages/flask_wtf/recaptcha/widgets.py", line 5, in <module>
    from werkzeug import url_encode
ImportError: cannot import name 'url_encode' from 'werkzeug' (/home/sid/.local/lib/python3.8/site-packages/werkzeug/__init__.py)
```

**Comment by philderbeast** [comment]
Switching branches to the active development branch (using `flask` instead of `formula_dev`) and rebuilding the docker container avoids this problem.

```
> git branch
  dev
* flask
  formula_dev
  master

> docker-compose build --no-cache flask-dev
> docker-compose up flask-dev
```
