### ISSUE TITLE
comp create_results gives error

### ISSUE THREAD

**Issue by kuaka** [kuaka/airscore#56]
running Comp().create_results in an error. It seems that it calls task.create_from_json
I don't understand why we are calling this but I guess it is because we are not using the DB for task results and it is trying to re-create the tasks to then score the comp. Perhaps the task result file format has changed and this has not been tested since.

from comp import Comp
comp, ref_id, filename =Comp().create_results(40)

Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "airscore/core/comp.py", line 392, in create_results
    task = Task.create_from_json(task_id=t.task_id, filename=t.file)
  File "airscore/core/task.py", line 1152, in create_from_json
    task.pilots.append(Pilot.from_result(task_id, pil))
  File "airscore/core/pilot.py", line 175, in from_result
    pilot.track.track_file = Track.from_dict(result)
  File "/airscore/core/track.py", line 214, in from_dict
    setattr(track, key, value)
AttributeError: can't set attribute

**Comment by kuaka** [comment]
fixed I believe.
